import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import clsx from 'clsx'
import { relative } from 'path'

const mont = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='bg-sky-900 to-indigo-600 text-slate-100'>

      <body className={clsx(mont.className, "relative min-h-screen")}>
        <Header />
        {children}
        <Footer />
        <div className='absolute inset-0 -z-50 max-h-screen background-gradient'></div>
      </body>
    </html>
  )
}
