// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  content_index: dynamic(() => import("./ContentIndex")),
  hero: dynamic(() => import("./Hero")),
  tech_stack: dynamic(() => import("./TechStack")),
  text_block: dynamic(() => import("./TextBlock")),
};
